### PR TITLE
Feature/enable mutli arch

### PR DESCRIPTION
**Pull request by pixiono**

### CODE REVIEW

**Review by sibalzer — CHANGES_REQUESTED** [review]
nm

**Review by sibalzer — APPROVED** [review]

**Comment by sibalzer** [comment]
ill test this in a different repro

**Comment by sibalzer** [comment]
FYI i still on it.

**Comment by pixiono** [comment]
@sibalzer Hey, sorry for the delay. My last commit should solve the issue.

**Comment by sibalzer** [comment]
😢 
<details>
<summary>Log</summary>
grafik
</details>

**Comment by b-reich** [comment]
Saw this PR to late -.-
Got something in my own repo.
https://github.com/b-reich/impfbot/tree/build_arm

**Comment by sibalzer** [comment]
apparently they need now rust in the cryptography libary and dropped default support for arm/v6 and arm/v7

**Comment by sibalzer** [comment]
wrong branch

**Pull request merged**
