### PR TITLE
Move import for gui elements

### PR DESCRIPTION
**Pull request by Muehli25**
Simple Fix for #88

### CODE REVIEW

**Comment by paulypeter** [comment]
That still wouldn't work when choosing to generate the config, or does it?

**Comment by Muehli25** [comment]
I just moved the import. It's working fine in ubuntu desktop and ubuntu server. (atleast on my machine :smile: )

**Comment by sibalzer** [comment]
I accept this as a temporary hotfix. But it shouldn't be the final solution. (contradicts PEP8, and the cli generation does not work on servers with this fix).

**Comment by paulypeter** [comment]
Could you try wrapping the tk import in a try-except block in `config-generator.py` instead?
Does it a raise a ModuleNotFoundError or an ImportError?
```
try:
    import tkinter as tk
    from tkinter import ttk
except Exception:
    ...
```

**Review by sibalzer — APPROVED** [review]

**Pull request merged**
