### PR TITLE
Config generation interface

### PR DESCRIPTION
**Pull request by paulypeter**

### CODE REVIEW

**Comment by paulypeter** [comment]
@sibalzer I implemented a somethat rudimentary GUI with a CLI as fallback and some simple validation checks.

Could you have a look at it?

**Comment by sibalzer** [comment]
Looks good.  (not tested yet)

I have also thought about refactor the config parameters. (currently very inconsistent with German and English, also cooldown fits better than sleep). But any changes, like yours to settings.py, would break compatibility with earlier configs.

I am currently working on making the code more readable and pythonic, refactor the config would also fit in that (with deprecated config support). 

I'll test the pr right now, i think we should start a beta branch with this pr.

**Review by sibalzer — APPROVED** [review]
I just finish the unit tests and then it can be merged

**Comment by paulypeter** [comment]
Do you want me to resolve the conflict?

**Comment by sibalzer** [comment]
Already done. I let the pr open for now.

**Comment by paulypeter** [comment]
Alright, perfect!

**Comment by sibalzer** [comment]
Aaaand tests are broken as expected (config keys). I'll fix that with my settings refactoring

**Pull request merged**
