### PR TITLE
Tutorial for using on android via termux

### PR DESCRIPTION
**Pull request by ronizzel**

### CODE REVIEW

**Review by sibalzer — CHANGES_REQUESTED** [review]
Nice!

Just two small changes:
1. SET_ANDROID.md -> SETUP_ANDROID.md
2.  In the readme a link under `### 📝 Anleitung - Schritt für Schritt` before the docker paragraph

**Comment by ronizzel** [comment]
A stupid question concerning 2.: how to link "internally" in the readme to the tutorial (which url)?
And another question, I forgot: I did'nt find a stable link like latest.tar.gz Maybe I'm blind? Now the tutorial needs to be changed with each update.

**Comment by ronizzel** [comment]
I think I answered stupid question 1 (hope it works like this)

**Comment by sibalzer** [comment]
htis should work: https://api.github.com/repos/sibalzer/impfbot/tarball

**Comment by paulypeter** [comment]
Wow, that's great!

**Comment by ronizzel** [comment]
Should work now

**Review by sibalzer — APPROVED** [review]

**Comment by sibalzer** [comment]
thanks!

**Pull request merged**
